spring:
  cloud:
    gateway:
      routes:
        - id : r1
          uri: http://localhost:8081/
          predicates:
            - Path=/Customers/**
        - id : r2
          uri: http://localhost:8082/
          predicates:
            - Path=/Account/**
  application:
    name: gateway_service
server:
  port: 8083





